# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
